### ISSUE TITLE
Is there any way to fix for node packages?

### ISSUE THREAD

**Issue by frederikhors** [dominikg/svite#68] opened 2020-09-22 10:24 UTC
## Problem

I really love Svite and Vite. Really.

After months of working with the defualt template (sveltejs/template) the difference is huge, both in terms of time and convenience.

But there is one thing that kills me inside.

Today I'm starting to try to use [rxDB](https://github.com/pubkey/rxdb) and honestly it feels like a perennial obstacle course: just to get it started!

**Yet that package is already an ESM!**

The problem I'm having is that it uses `pouchdb` which in turn is made up of many packages that also use imports such as:

```js
import EE from 'events'
```

I know this is wrong because we're running it in browser. And I'm opening issues everywhere to address this (e.g.: https://github.com/pouchdb/pouchdb/issues/8186).

But there is also another aspect of the matter: today there are thousands of STABLE libraries that work like this and WE CANNOT IGNORE THEM.

## Questions

**May I ask you if you know a (temporary) way to solve?**

Can we use (overriding) Rollup's plugins for node utils?

Otherwise I'll be forced - crying - to go back to the old default Svelte template, I repeat, crying.

Thanks for your invaluable work!

**Comment by frederikhors** [comment] 2020-09-22 12:54
Maybe `rollup-plugin-node-polyfills` is the way to go.

But how to add it to Rollup?

**Comment by dominikg** [comment] 2020-09-22 19:09
Not sure what svite could do about this. If you are unable to use deep imports to avoid errors like this, the library is incompatible.

See https://github.com/dominikg/svite#imports-of-commonjs-modules-dont-work-in-svite-dev

It would be great if you could share a minimal reproduction setup as a git repo anyways.

I totally do not recommend to add node polyfills or fake types, this is likely going to nose-dive once you try to use that code in the browser.

**Comment by frederikhors** [comment] 2020-09-22 19:21
I don't know what to do.

`rollup-plugin-node-polyfills` works with default Svelte template and I know this is wrong, but I need to work! :smile:

**Comment by frederikhors** [comment] 2020-09-22 19:21
I will create a minimal repo.

**Comment by frederikhors** [comment] 2020-09-25 12:37
Thanks for your answer.

> If you are unable to use deep imports to avoid errors like this, the library is incompatible.

I have already solved this problem; now there is another.

In a new Svite minimal project if you try to import something ([RxDB](https://github.com/pubkey/rxdb) in this case) which imports something like `pouchdb` which has some deps that has some import like: `import EE from 'events'` you cannot. Error, one after another.

But this also in my Rollup project.

I was able to solve using [@rollup/plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve) but I can't understand how to do it with Vite/Svite.

Is the problem more understandable now?

**Comment by dominikg** [comment] 2020-09-26 13:21
Please share a repository which demonstrates your issue. Right now i think it is the way you are importing from rxdb thats causing it.

Looking through the rxdb examples, eg. https://github.com/pubkey/rxdb/blob/master/examples/angular/src/app/services/database.service.ts

It seems very possible to use deep imports and pouchdb adapters to avoid using code that imports node dependencies.

I don't think using rollup-plugin-node-polyfills - even if it would make your code technically work - would create the result you are looking for.

ps. the related upstream issue got closed https://github.com/vitejs/vite/issues/847 . Unless you can provide a clean reproduction i'm afraid this one is going to be closed too.

**Comment by frederikhors** [comment] 2020-09-27 09:07
Ok. I tried everything, deep imports and not.

My minimal reproduction repo is here: https://github.com/frederikhors/svite-template-minimal/tree/add-rxdb.

**Comment by frederikhors** [comment] 2020-09-27 09:13
Errors in console if you use that `vite.config.js`:

```
[vite] Dep optimization failed with error:
Dependency pouchdb-utils is attempting to import Node built-in module events.
This will not work in a browser environment.
Imported by: node_modules\pouchdb-utils\lib\index-browser.es.js

Tip:
Make sure your "dependencies" only include packages that you
intend to use in the browser. If it's a Node.js package, it
should be in "devDependencies".

If you do intend to use this dependency in the browser and the
dependency does not actually use these Node built-ins in the
browser, you can add the dependency (not the built-in) to the
"optimizeDeps.allowNodeBuiltins" option in vite.config.js.
```

And also if I add this in vite.config.js:

```js
module.exports = {
    optimizeDeps: {
        include: [
            'rxdb',
        ],
        allowNodeBuiltins: [
            'rxdb',
            'pouchdb-replication',
            'pouchdb-core',
            'pouchdb-utils',
        ]
    },
}
```

I still have this in browser:

`GET http://localhost:3000/@modules/events?import net::ERR_ABORTED 404 (Not Found)`

and console:

```
Error: ENOENT: no such file or directory, stat 'events'
    at Object.statSync (fs.js:1016:3)
    at Object.statSync (projects\svite-template-minimal\node_modules\graceful-fs\polyfills.js:308:16)
    at cachedRead (projects\svite-template-minimal\node_modules\vite\dist\node\utils\fsUtils.js:24:45)
    at serve (projects\svite-template-minimal\node_modules\vite\dist\node\server\serverPluginModuleResolve.js:35:23)
    at projects\svite-template-minimal\node_modules\vite\dist\node\server\serverPluginModuleResolve.js:67:20
    at dispatch (projects\svite-template-minimal\node_modules\koa-compose\index.js:42:32)
    at projects\svite-template-minimal\node_modules\vite\dist\node\server\serverPluginEnv.js:24:16
    at dispatch (projects\svite-template-minimal\node_modules\koa-compose\index.js:42:32)
    at projects\svite-template-minimal\node_modules\vite\dist\node\server\serverPluginHtml.js:42:15
    at dispatch (projects\svite-template-minimal\node_modules\koa-compose\index.js:42:32)
```

**Comment by dominikg** [comment] 2020-09-27 11:36
The same thing happens in a vanilla vite project so this is not caused by svite.

You also cannot use rollup-plugin-node-polyfills right now as it expects to be included after rollup-plugin-commonjs
a fix for that has already landed in vite master but it hasn't been released. See https://github.com/vitejs/vite/issues/728

I also saw that you commented on that issue. Please post stuff like that and share your findings here. I just dug into this for an hour to arrive at a point where it seems you have already had been.

**Comment by frederikhors** [comment] 2020-09-27 12:12
So at least I know now I'm not crazy! :smile:

**Comment by dominikg** [comment] 2020-09-27 12:42
I have added a reproduction to the upstream issue vitejs/vite#847 please continue any discussion there as svite is not the cause of this.

**Closed by dominikg** 2020-09-27 12:42 UTC
Labels: bug, upstream

**Comment by frederikhors** [comment] 2020-09-30 19:56
Can I ask you why did you used `exclude` below?

```js
optimizeDeps: {
    include: ['rxdb/plugins/core'], // try to limit scope of optimized module
    exclude: ['rxdb'],
```

**Comment by dominikg** [comment] 2020-09-30 20:13
just a try to prevent vite from optimizing the whole rxdb module. hopefully not needed when vite works with node-polyfills
